# Generated by Django 3.0.1 on 2021-04-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200211_1303'),
        ('products', '0002_auto_20210428_1153'),
    ]

    operations = [
    ]
